language: erlang

otp_release:
  - 18.0
  - 17.5
  - R16B03-1
  - R14B04

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libmozjs-dev
  - git clone https://github.com/apache/couchdb

before_script:
  - cd couchdb
  - ./configure --disable-docs --disable-fauxton
  - cp -r ../!(couchdb) ./src/couch_peruser
  - make

script:
  - rebar setup_eunit
  - BUILDDIR=`pwd` rebar -r eunit apps=couch_peruser

cache: apt

before_deploy:
  - name=${PWD##*/}
  - cd ..
  - tar czf "$name.tar.gz" "$name"

deploy:
  provider: releases
  api_key:
    secure: GgNZWF4A0xs3i7twrOK9XhSomgHw4EU6Fx/+pp5n1+kupKfxc/mCPFew9YFk4AEHa71xedqsMlfvzaF4kBgJjPBplO1wcgEtsNddBQyMTzR8T3AJYImiiu6CIVnZcJuwjWfsL5fGcvn/ASu1L+c+b2nDXfqiXX6MvOyL2f6H/BYvA/GXbkmMfNKrOGC+Br9GdZ193E5cchu7NdAZj7ihVUo4+a6JpruoZ6EqMcb8k7EKYPIW/HR+XCc8ndZJPiOOSos/DEsDkosOdmsmS705I/EuvwvJXeZHGHVXSNdwb0WAk5tuoQL7lcI5KljtC7o3bs5OoCRiqQC9f+74SaUW2pEMWdRKfip2X8cl36h2EWUROqscQUKnBlEm6EdfL23roxMdEQUoZ2LKtc5SoFHxArW60nnEVhJRyrxx58sO057nVWiKkyBoYIAuWEXe9Fdi30zAaPdpbEFar7nNMbvf0WEirlHLRN6Dk57jDZ4x6BIXYBQQtUpYkfLFJw9moysxZaHn1gjKfNK6TV5KKWCh0iqqt9CkpR/Q8yh4Q5Owl3c3/EiQDyNwUCJCQQ9CeDkVluxPYO/YOKBs4hUpuz1jawkdEkx/hZrT1TBUvu65EjG1nuZOXn9EsKZxKKAI3rRmdLQQOcJGdGAHWsaMUEi/g7AdGIHEAD0nnvl+h5gJ3XU=
  file: couchdb-peruser.tar.gz
  on:
    repo: tlvince/couchdb-peruser
    tags: true
